- README.md
- package.json
- yarn.lock
The README now explains how this extension under development can be
included in a Theia app, even though it is not expected to work right
now.
Signed-off-by: Geneviève Bastien <gbastien@versatic.net>
> Add instructions to run the extension in Theia

- vscode-trace-webviews/src/trace-explorer/opened-traces/vscode-trace-explorer-opened-traces-widget.tsx
- vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx
Signed-off-by: Bernd Hufmann <Bernd.Hufmann@ericsson.com>
> Make VsCode extension work with latest theia-trace-extension changes

- vscode-trace-extension/src/common/signal-converter.ts
- vscode-trace-extension/src/trace-explorer/opened-traces/trace-explorer-opened-traces-webview-provider.ts
- vscode-trace-extension/src/trace-explorer/views/trace-explorer-available-views-webview-provider.ts
- vscode-trace-webviews/src/common/vscode-signal-converter.ts
- vscode-trace-webviews/src/trace-explorer/opened-traces/vscode-trace-explorer-opened-traces-widget.tsx
- vscode-trace-webviews/src/trace-explorer/views/vscode-trace-explorer-views-widget.tsx
- vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx
> Properly deserialize Experiment in signals to create BigInt timestamps

- vscode-trace-extension/package.json
- vscode-trace-extension/src/extension.ts
- vscode-trace-extension/src/trace-explorer/trace-tree.ts
- vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
- vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx
Support of selection of data provider in overview view
Add command to open overview view when closed (`CTRL+SHIFT+P`+`Open Overview View`)
Fixes #55
> Fix overview view functionality

- README.md
This PR is simply made of four (4) trivial yet distinct commits.
> Fix these while starting to use README.md and this repo

- yarn.lock
> Upgrade to latest trace viewer components and dependencies

- vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
> Initialize theme when opening new trace from file explorer

- .github/workflow/build.yml
- vscode-trace-extension/.eslintrc.js
2 commits:
- Fix linting
- Add basic CI workflow for build and linting
> Add basic CI workflow for build and linting

- CONTRIBUTING.md
- README.md
- vscode-trace-extension/package.json
- vscode-trace-webviews/package.json
> Replace obsolete theia-ide with eclipse-cdt-cloud

- vscode-trace-extension/package.json
- vscode-trace-extension/src/extension.ts
- vscode-trace-extension/src/trace-explorer/opened-traces/trace-explorer-opened-traces-webview-provider.ts
- vscode-trace-extension/src/trace-explorer/trace-tree.ts
- vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
- vscode-trace-webviews/src/trace-explorer/opened-traces/vscode-trace-explorer-opened-traces-widget.tsx
- Add opened traces contribution to openedTracesView 
- Show file picker dialog to select experiment
- Update opened traces and available views after opening
fixes #61
> Add open button in "Open Traces" view

- vscode-trace-extension/package.json
> Fix typo in ./vscode-trace-extension/package.json

- vscode-trace-extension/package.json
> Use correct icon for Open Overview View button in light theme

- .github/workflows/build.yml
see https://github.com/actions/setup-java
> Use Java 17 in workflow ui-test

- yarn.lock
Signed-off-by: Patrick Tasse <patrick.tasse@gmail.com>
> Uplift timeline-chart to latest version

- vscode-trace-common/src/messages/vscode-message-manager.ts
- vscode-trace-extension/package.json
- vscode-trace-extension/src/extension.ts
- vscode-trace-extension/src/trace-explorer/time-range/trace-explorer-time-range-data-webview-provider.ts
- vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
- vscode-trace-webviews/src/style/trace-viewer.css
- vscode-trace-webviews/src/trace-explorer/opened-traces/vscode-trace-explorer-opened-traces-widget.tsx
- vscode-trace-webviews/src/trace-explorer/time-range/index.css
- vscode-trace-webviews/src/trace-explorer/time-range/index.tsx
- vscode-trace-webviews/src/trace-explorer/time-range/vscode-time-range-data-widget.tsx
- vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx
- vscode-trace-webviews/webpack.config.js
- yarn.lock
Integrates the TimeRangeDataWidget to VSCode Trace Extension's trace explorer.
This requires changes in the theia-trace-extension repo: https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/991
> TimeRangeDataWidget CodeOSS Port

- .github/workflows/ci-cd.yml
- .github/workflows/license-check-workflow.yml
- .github/workflows/release.yml
- .vscode/settings.json
- README.md
> update to node 18

- vscode-trace-extension/src/extension.ts
> Implement workaround for Theia compatibility of welcome page

- vscode-trace-common/package.json
- vscode-trace-common/src/messages/vscode-message-manager.ts
- vscode-trace-extension/package.json
- vscode-trace-extension/src/extension.ts
- vscode-trace-extension/src/trace-explorer/properties/trace-explorer-properties-view-webview-provider.ts
- vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
- vscode-trace-webviews/package.json
- vscode-trace-webviews/src/trace-explorer/properties/vscode-trace-explorer-properties-widget.tsx
- vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx
- yarn.lock
This commit addresses the persistence of item properties and handling of the new ItemPropertiesSignalPayload.
Fixes #202
> Handle new Item Properties Signal Payload

- vscode-trace-extension/src/trace-explorer/opened-traces/trace-explorer-opened-traces-webview-provider.ts
- vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
This happens when opening multiple traces and manually switching newly opened panels.
- The main fix is to avoid calling panel.reveal() when the trace-viewer-webview-panel is processing the EXPERIMENT_SELECTED signal. This call is not only unecessary but will also interfere with ongoing propagation of TRACEVIEWERTAB_ACTIVATED and EXPERIMENT_SELECTED signals.
- Only call setExepriment() on the panel instance if it was created new, hence it was reopened, and don't call on the panel if the panel is already open. For that a new public static method getExistingPanel was added to the TraceViewerPanel class.
- Only call fireExperimentSelectedSignal() right after calling fireTraceViewerTabActivatedSignal() if the open-traces webview is not visible. If this webview is visible, then the webview …
> Fix endless switching between experiment panels

- vscode-trace-extension/src/trace-explorer/time-range/trace-explorer-time-range-data-webview-provider.ts
> Add codicon path to localResourceRoots for time range data webview

- vscode-trace-common/package.json
- vscode-trace-extension/package.json
- vscode-trace-webviews/package.json
- yarn.lock
This PR bumps the version of traceviewer-base, and traceviewer-react-components
> Bump traceviewer packages version

- vscode-trace-common/package.json
- vscode-trace-extension/package.json
- vscode-trace-webviews/package.json
- yarn.lock
traceviewer-base: v0.2.5
traceviewer-react-components: v0.2.5
timeline-chart: v0.3.2
tsp-typescript-client: v0.4.2
> Upgrade traceviewer components

- RELEASE
- lerna.json
- vscode-trace-common/package.json
- vscode-trace-extension/package.json
- vscode-trace-webviews/package.json
> Release v0.2.7 (Patch)

- README.md
> Update remote-ssh description with open-remote-ssh extensions on OpenVsx

- RELEASE
- lerna.json
- vscode-trace-common/package.json
- vscode-trace-extension/package.json
- vscode-trace-webviews/package.json
New version of `Trace Viewer for VSCode`, with updated dependencies and a few other improvements.
> Release v0.2.9 (Patch)

- RELEASE
- lerna.json
- vscode-trace-common/package.json
- vscode-trace-extension/package.json
- vscode-trace-webviews/package.json
> Release v0.3.0 (Minor)

- RELEASE
- lerna.json
- vscode-trace-common/package.json
- vscode-trace-extension/package.json
- vscode-trace-webviews/package.json
> Release v0.3.2 (Patch)

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
- SECURITY.md
This PR adds an issue and PR template in this repo, heavily inspired from those of the Eclipse Theia project (look at the raw files to see the parts that are comments):
[Theia Issue templace](https://github.com/eclipse-theia/theia/tree/master/.github/ISSUE_TEMPLATE) (composed of a few files)
[Theia PR template](https://raw.githubusercontent.com/eclipse-theia/theia/refs/heads/master/.github/PULL_REQUEST_TEMPLATE.md)
The new issue template will not be visible here until this PR is merged. To see what this will look-like, look at the [theia-trace-extension - create new issue](https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/new/choose), where we already added the same templates.
For the PR template, I'm using it right here (manually copied and filled-in). Much of the …
> Add basic issue and pull-request templates

- package.json
- vscode-trace-common/package.json
- vscode-trace-extension/package.json
- vscode-trace-webviews/package.json
- yarn.lock
update to latest "traceviewer" packages (0.6.0):
"traceviewer-base" and "traceviewer-react-components"
Also: 
- perform yarn upgrade
- fix some of the peer dependencies warnings
- remove a few dependencies not needed any more
- remove a few package.json blocks that  had no effect
A bit more details the dependencies:
Yarn provides some useful warnings once the dependencies are resolved. In some cases, it was possible to update versions of dependencies to satisfy the warnings, in some other cases I found the dependencies in question were no longer apparently used anywhere, and so I removed them.
In some cases I moved "dev" dependencies to the root package.json since they are applicable to all components in the yarn workspace (e.g. eslint related dependencies).
Make sure CI passes
N/A
> update to latest "traceviewer" packages (0.6.0)

- package.json
- yarn.lock
Upgrade lerna to v8.x.
Successful build.
> Upgrade lerna to v8.x

- configs/license-check-exclusions.json
- vscode-trace-common/package.json
- vscode-trace-extension/package.json
- vscode-trace-webviews/package.json
- yarn.lock
Upgrade to latest traceviewer packages and tsp-typescript-client
- traceviewer-base and traceviewer-react-components: v0.7.2
https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1184
- tsp-typescript-client: v0.6.0
https://github.com/eclipse-cdt-cloud/tsp-typescript-client/pull/128
Note: Ignore license check error because it's believed to be license-compatible, but still under review:
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/19938
Successful CI run.
N/A
> Upgrade to latest traceviewer packages and tsp-typescript-client

- vscode-trace-common/package.json
- vscode-trace-common/src/messages/vscode-messages.ts
- vscode-trace-common/src/types/customization.ts
- vscode-trace-extension/package.json
- vscode-trace-extension/src/extension.ts
- vscode-trace-extension/src/json-editor/file-service.ts
- vscode-trace-extension/src/json-editor/json-editor.ts
- vscode-trace-extension/src/json-editor/schema-service.ts
- vscode-trace-webviews/package.json
- vscode-trace-webviews/src/common/vscode-message-manager.ts
- vscode-trace-webviews/src/trace-explorer/available-views/vscode-trace-explorer-views-widget.tsx
- yarn.lock
This PR introduces a JSON configuration editor to enable users to customize trace output configurations. The implementation provides a complete editing workflow with validation, schema support, and file operations.
- JSON editor with schema validation for customizing trace outputs
- UI toolbar with submit, save, and load operations
- Schema-based validation with error reporting
- Support for saving and loading configurations from files
- Integration with the Trace Explorer's available views
- Added `JsonConfigEditor` class to manage editing sessions and validation
- Created `SchemaService` for JSON schema operations using Ajv
- Added `FileService` for file I/O operations
- Implemented new message types for communication between components
- Added toolbar commands for the editor UI
- Added …
> Add JSON Configuration Editor for Trace Output Customization

- vscode-trace-common/package.json
- vscode-trace-extension/package.json
- vscode-trace-webviews/package.json
- yarn.lock
Upgrade traceviewer components, tsp-typescript-client and timeline-chart
- traceviewer-base and traceviewer-react-components: v0.9.0 https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1201
- tsp-typescript-client: v0.7.0 https://github.com/eclipse-cdt-cloud/tsp-typescript-client/pull/131
- timeline-chart: v0.4.2 https://github.com/eclipse-cdt-cloud/timeline-chart/pull/320
Successful CI. Open some traces and views for sanity checks.
N/A
> Upgrade traceviewer components, tsp-typescript-client and timeline-chart

- RELEASE
- lerna.json
- vscode-trace-common/package.json
- vscode-trace-extension/package.json
- vscode-trace-webviews/package.json
Release v0.5.2 (Patch)
Successful CI.
N/A
> Release v0.5.2 (Patch)

- vscode-trace-common/package.json
- vscode-trace-extension/package.json
- vscode-trace-webviews/package.json
- yarn.lock
traceviewer-base and traceviewer-react-components: v0.9.1 https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1212
Successful CI. Do some manual sanity tests.
N/A
> Upgrade traceviewer components to v0.9.1

- RELEASE
- lerna.json
- vscode-trace-common/package.json
- vscode-trace-extension/package.json
- vscode-trace-webviews/package.json
Minor release (0.6.0) due to bugfixes and added feature (i.e. removeTrace command).
Successful CI
N/A
> Release v0.6.0 (Minor)

- vscode-trace-extension/src/json-editor/json-editor.ts
VSCode does not allow developers to have a simple 'onThisFileClose' or 'onAnyFileClose' event. So we had to use a different event to trigger the 'onClose' event handler for customized view configuration.
The one that was being used `onDidChangeVisibleTextEditors` was not working as expected.  The event handler has been changed to `onDidChangeTabs`.
Fixes https://github.com/eclipse-cdt-cloud/vscode-trace-extension/issues/334
Open, close, drag and drop files around the IDE with the config editor open.  It should not bug out
Continued customized view improvements
- [ x] As an author, I have thoroughly tested my changes and carefully followed the instructions in this template
> Properly handle on file close events
