.gitignore
README.md
package.json

- Add script in package.json to download and run Trace Compass server
- Add script in package.json to download sample traces
- General clean-up of README.md and for how to run the extension
- Remove SSL requirement description in README for running in Theia
- Better explain packaging and how to run the extension
- Fix typos and linting errors
-  Provide details about webviews and their communication to the README.md
- Provide a sequence diagram illustrating the communication between 2 webviews.

Improve description in README.md and provide scripts to download server and example traces

---

vscode-trace-webviews/src/style/trace-viewer.css

 
Changes made:
 Added missing CSS mappings from theia for views
 
This will fix view menus having transparent background
Fixes #65
 
Signed-off-by: Neel Gondalia ngondalia@blackberry.com

Fixed styling of view menus

---

CONTRIBUTING.md
README.md
SECURITY.md

After the move to Eclipse CDT cloud project and it's GitHub organization add CONTRIBUTING.md and SECURITY.md.

Add CONTRIBUTING.md and SECURITY.md files to the repository

---

vscode-trace-webviews/src/trace-explorer/opened-traces/vscode-trace-explorer-opened-traces-widget.tsx

The wrong object was being passed to the parser.
Fixes #63.
Signed-off-by: Rodrigo Pinto <rodrigo.pinto@calian.ca>

Fix refresh of views when switching trace tabs

---

vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
vscode-trace-webviews/src/style/trace-viewer.css
vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx

The background color of some elements of the extension, like the charts, was not being changed when a new theme was selected for VSCode.
Now, the extension recognizes if the theme is light or dark and changes the background of the charts accordingly.
https://user-images.githubusercontent.com/88502808/217006304-6c9f9c31-8bcd-444b-919a-6f79e7d89b78.mp4
Fixes #8.
Signed-off-by: Rodrigo Pinto <rodrigo.pinto@calian.ca>

Support of changing the theme

---

vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx

Adds window resize handlers to the trace-explorer-views-widget.tsx. These are implemented the same way as in theia-trace-extension trace-viewer.tsx widget.
Fixes: #9

Support Resizing of Charts

---

vscode-trace-webviews/src/style/trace-viewer.css

Added missing css mappings to fix overview view selection menu style:
Codicons are not integrated in webviews by default, due to which the close ('x') button on the top-right is missing. The following issue talks about how to let the webview load VS Code's bundled codicons: https://github.com/microsoft/vscode/issues/95199. I was unable to get this working properly though, for me the icons were showing up as an empty box, but the button was working:
[Screen Recording 2023-02-14 at 12.21.49 PM.webm](https://user-images.githubusercontent.com/92893187/219276229-639c8c86-50ff-459d-be95-e332942e71f8.webm)
I would suggest creating a separate issue to bundle codicons and get all webview codicon icons to show, or replace the  codicon icon with svg in `abstract-dialog-component.tsx`
fixes #76

Fix Overview view selection menu style

---

vscode-trace-extension/src/trace-explorer/available-views/trace-explorer-available-views-webview-provider.ts
vscode-trace-extension/src/trace-explorer/opened-traces/trace-explorer-opened-traces-webview-provider.ts
vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
vscode-trace-webviews/src/trace-explorer/available-views/vscode-trace-explorer-views-widget.tsx

Make sure that selection of current experiments are persisted and restored in both views by sending and handling tabActivatedSignal and experimentSelectedSignal at relevant places.
Also, fix clearing of views and selection when trace panels are closed.
Fixes #64

Refresh "VIEWS" and "TRACES" after being minimized and re-opened

---

package.json
vscode-trace-extension/package.json
vscode-trace-webviews/package.json
vscode-trace-webviews/src/trace-explorer/available-views/index.tsx
vscode-trace-webviews/src/trace-explorer/opened-traces/index.tsx
vscode-trace-webviews/src/trace-explorer/properties/index.tsx
vscode-trace-webviews/src/trace-viewer/index.tsx
vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx
yarn.lock

The trace viewer dependencies updated to React 18. Update also the webviews for that.
Upgrade to the latest traceviewer-base and traceviewer-react-components.

Upgrade to React 18

---

vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx

When running in Theia, the set-tspClient and set-experiment are received right after each other and the setting of the tspClient in the state has not been finalized since it's done asynchronously. So, when the set-experiment signal is handled the tspClient in the react state is still undefined and the available outputs cannot be retrieved and hence no overview is shown.
The solution is to provide the experiment in the set-tspClient signal if available and hence the outputs can be retrieved and the overview view can be populated.

Fix showing of overview view with default when running in Theia

---

vscode-trace-extension/src/trace-explorer/opened-traces/trace-explorer-opened-traces-webview-provider.ts

- Remove the `closeTrace` case lines of code, falling through `deleteTrace`'s which are identical.
- Based on the related SonarLint warning in VS Code.

opened-traces: Remove redundant case code lines

---

vscode-trace-webviews/webpack.config.js

- Since commit `1287ba25` introduced the currently required `"inline-source-map"` value for that key.
- The other, earlier commit `16fe6129` initialized that key prior, to a previously wanted value.
- This fix is also based on the related SonarLint warning in VS Code.

webpack config: Remove obsoleted/extra devtool key

---

vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
vscode-trace-webviews/src/common/vscode-message-manager.ts
vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx
yarn.lock

Webviews run in isolated contexts that cannot access local resources. Because of this webviews could an issue with opening hyperlinks.
- Suggested fix is to use showSaveDialog from vscode api
- Users can choose file name/path
- Show success/error message after
- Depends on signal added in https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/938
Fixes #66

Export DataTree to csv through showSaveDialog

---

vscode-trace-webviews/src/trace-explorer/opened-traces/vscode-trace-explorer-opened-traces-widget.tsx

* Appropriate signal handling for removed traces
* Edited behaviour for the "X" button in the "opened traces" view
Fixes #104
Signed-off-by: Neel Gondalia ngondalia@blackberry.com

Disposes trace panel when trace removed

---

vscode-trace-extension/src/extension.ts
vscode-trace-extension/src/trace-explorer/available-views/trace-explorer-available-views-webview-provider.ts
vscode-trace-extension/src/trace-explorer/opened-traces/trace-explorer-opened-traces-webview-provider.ts
vscode-trace-extension/src/trace-explorer/trace-tree.ts
vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
vscode-trace-extension/src/utils/trace-server-status.ts
vscode-trace-webviews/src/common/tsp-client-provider-impl.ts
vscode-trace-webviews/src/common/vscode-message-manager.ts
vscode-trace-webviews/src/trace-explorer/available-views/vscode-trace-explorer-views-widget.tsx
vscode-trace-webviews/src/trace-explorer/opened-traces/vscode-trace-explorer-opened-traces-widget.tsx
vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx

Add a contextual (secondary, right-side) VS Code status bar item, that renders the current trace server status. Have the extension context pass this status service to each active web-view provider, for them to update the rendered status upon every related message from the view.
Have `TraceExplorerOpenedTracesViewProvider` pass its status service to the `TraceViewerPanel` upon using it, in turn. Without this, there are instances where the latest server status isn't shown as expected. Keep this undefined in `trace-tree.ts` where that is not required.
This makes the server status listener-based. Add this connection listener through the `TspClientProvider` constructor, thus consistently use the latter across. This means also using it in the `TraceViewerContainer` constructor, instead of …

Render new trace server connection status bar item

---

README.md
vscode-trace-extension/src/extension.ts
vscode-trace-extension/src/utils/trace-extension-logger.ts

This will create an output channel for the trace extension 
in the output panel of vscode. This can be used to provide 
information to users.
Signed-off-by: Neel Gondalia ngondalia@blackberry.com

Added an output channel for logging

---

README.md

Fix the two markdownlint warnings [1] below, in VS Cod{e|ium}.
[1] MD031: Fenced code blocks should be surrounded by blank lines.

README: Fix markdownlint about missing blank lines

---

.github/workflows/build.yml
.gitignore
README.md
package.json
playwright.config.ts
vscode-trace-extension/package.json
vscode-trace-extension/src/test/extension-test.spec.ts
yarn.lock

Add and configure Playwright in vscode-trace-extension package.
Add extension-test.spec.ts with a few simple tests.
Ignore and exclude test files and folders from build and version control.
Partially fixes Issue #34

Configure integration tests with Playwright

---

yarn.lock

Upgrades to recent updates in `timeline-chart`, `traceviewer-base` and `react-components`:
- timeline-chart: "0.3.0-next.20230419183309.9e0527f.0"
- traceviewer-base/react-components: "0.2.0-next.20230424153016.14a2611.0"

Upgrade traceviewer-base/react-components and timeline-chart versions

---

vscode-trace-webviews/src/trace-viewer/index.css

The body and root div were not filling 100% of the height.  This led to problems displaying the placeholder message when a user hasn't selected any outputs.
Makes body and root div height and width 100%.  Centers the placeholder message on the screen.  Fixes #112.

Fix padding of placeholder message

---

vscode-trace-extension/package.json
vscode-trace-extension/src/extension.ts
vscode-trace-extension/src/trace-explorer/trace-tree.ts
vscode-trace-extension/src/trace-viewer-panel/keyboard-shortcuts-panel.ts
vscode-trace-webviews/src/style/trace-viewer.css
vscode-trace-webviews/src/trace-explorer/shortcuts/index.css
vscode-trace-webviews/src/trace-explorer/shortcuts/index.tsx
vscode-trace-webviews/src/trace-explorer/shortcuts/vscode-trace-explorer-shortcuts-widget.tsx
vscode-trace-webviews/webpack.config.js

VS Code intentionally blocks modals in webviews. See [this issue](https://github.com/microsoft/vscode/issues/67109) for more details on why. The recommendation is to use a panel if the content cannot fit in an information message.
Demo:
[shortcutsPanel.webm](https://github.com/eclipse-cdt-cloud/vscode-trace-extension/assets/92893187/a3fda5c5-bf98-46c4-8f95-d145951470bd)
Note: If the panel already exists the command will bring it to the foreground
Panel can be triggered by:
1) Clicking info icon that appears in toolbar
2) Using VSCode’s ‘find command’ search:
3) Using keybinding 'CTRL/command + F1'
Depends on https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/978
Helps fix #117

Trace viewer shortcuts panel

---

vscode-trace-extension/package.json
vscode-trace-extension/src/extension.ts

Add two commands for a sibling extension such as [1] to use.
- These two commands are hidden from the Command Palette,
- as meant for [1] to update the Trace Server status bar item upon confirmed server start/stop.
[1] https://github.com/eclipse-cdt-cloud/vscode-trace-server
Contributes to fixing Issue #15.

extension: Support hidden server status commands

---

vscode-trace-common/src/messages/vscode-message-manager.ts
vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx

Use constants for undo, redo and updateZoom vscode messages instead of hard-coded strings.

Use constants for undo, redo and updateZoom vscode messages

---

vscode-trace-common/src/messages/vscode-message-manager.ts
vscode-trace-extension/package.json
vscode-trace-extension/src/trace-explorer/opened-traces/trace-explorer-opened-traces-webview-provider.ts
vscode-trace-webviews/src/style/trace-viewer.css
vscode-trace-webviews/src/trace-explorer/opened-traces/vscode-trace-explorer-opened-traces-widget.tsx

- Trace explorer panel provides an open trace button when experiments are 0
- Available views and properties webviews are hidden when experiments are 0
- Show the above 2 webviews when user opens an experiment
Fixes #110

Show placeholder view when no experiments are open

---

vscode-trace-common/src/client/tsp-client-provider-impl.ts
vscode-trace-webviews/src/trace-explorer/available-views/vscode-trace-explorer-views-widget.tsx
vscode-trace-webviews/src/trace-explorer/opened-traces/vscode-trace-explorer-opened-traces-widget.tsx
vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx

This is to be able to re-use `tsp-client-provider-impl` in the extension package as well.

Move tsp-client-provider-impl.ts to vscode-trace-common package

---

vscode-trace-common/src/messages/vscode-message-manager.ts
vscode-trace-extension/src/extension.ts
vscode-trace-extension/src/trace-explorer/opened-traces/trace-explorer-opened-traces-webview-provider.ts
vscode-trace-webviews/src/trace-explorer/opened-traces/vscode-trace-explorer-opened-traces-widget.tsx

With this the open traces view is populated with the open traces on the server.
Contributes to fixing Issue #15

Refresh open traces view after trace server started notification

---

vscode-trace-common/src/messages/vscode-message-manager.ts
vscode-trace-extension/package.json
vscode-trace-extension/src/extension.ts
vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx

- VSCode extensions currently do not support dynamic context menus or submenus: https://github.com/microsoft/vscode/issues/110218
- A recommendation was to use Quick Pick's instead: https://code.visualstudio.com/api/ux-guidelines/quick-picks
- Toolbar buttons have to be statically defined in package.json, making use of `setContext` commands to show/hide the markers toolbar buttons
Fixes #39

Add support for view markers

---

vscode-trace-extension/src/extension.ts

This change uses the vscode-trace-server commands to start a trace server and when the server is started it will perform the pending open command.
This change relies on the [vscode-trace-server](https://github.com/eclipse-cdt-cloud/vscode-trace-server) extension.
In a future release an API can be introduced so that an extension can register the start/stop commands and also the started notification. This future enhancement would decouple the vscode-trace-extension with the [vscode-trace-server](https://github.com/eclipse-cdt-cloud/vscode-trace-server) implementation.
Fixes #15

Automatic start trace server when user requests to open a trace

---

vscode-trace-common/src/client/tsp-client-provider-impl.ts

Since each webview has it's own RestClient which will update the status bar for the trace server, some webviews might not have the correct status because they haven't sent any TSP messages and the initial state of disconnect is propagated to the status bar. This can lead to an incorrect status bar message for the trace server.
This commit does a health check call to the back-end when the tspclient is created. With this all webviews will have the correct state.
Fixes #160

Fix status bar after starting trace server during open trace

---

vscode-trace-webviews/src/trace-explorer/opened-traces/vscode-trace-explorer-opened-traces-widget.tsx

Before, when re-opening an experiment right after the trace server started, the Experiment didn't have the start and end time set and the Experiment was still CLOSED.
This patch triggers a fetchExperiment call to open the experiment and to get the current start time and end time.
This patch is needed to fix an issue found with #152.
Fixes #165

Update experiment when re-opening an existing experiment on the server

---

README.md
vscode-trace-extension/src/extension.ts
vscode-trace-extension/src/external-api/external-api.ts
vscode-trace-extension/src/trace-explorer/available-views/trace-explorer-available-views-webview-provider.ts
vscode-trace-extension/src/trace-explorer/opened-traces/trace-explorer-opened-traces-webview-provider.ts
vscode-trace-extension/src/trace-explorer/properties/trace-explorer-properties-view-webview-provider.ts
vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
vscode-trace-extension/src/utils/trace-extension-webview-manager.ts

This commit provides an external API that can be used by other extensions to communicate with the base trace extension. The current API provides a way to retrieve the active experiment as well as fire events and register callbacks. This is the initial API and will be further expanded in future commits.
Fixes #140

Implemented external API

---

vscode-trace-extension/src/trace-explorer/available-views/trace-explorer-available-views-webview-provider.ts
vscode-trace-extension/src/trace-explorer/opened-traces/trace-explorer-opened-traces-webview-provider.ts
vscode-trace-extension/src/trace-explorer/properties/trace-explorer-properties-view-webview-provider.ts
vscode-trace-extension/src/trace-viewer-panel/keyboard-shortcuts-panel.ts
vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts

Makes all URI builders utilize webview.asWebviewUri method.  This ensures that the files can be served to remote clients.

Use webview.asWebviewUri for generating script paths.

---

yarn.lock

New version is: 0.2.0-next.20230714144744.f65b9ed.0
This will pull in some improvements for the Events Table. 

Upgrade traceviewer-base/react-components versions

---

vscode-trace-common/src/messages/vscode-message-manager.ts
vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx
yarn.lock

This commit handles the new Output_Data_Changed signal in the trace viewer container. This signal
notifies the appropriate outputs to refresh/re-fetch data from the server and re-render.
This is the follow up commit of https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1006

Propogate Output Data Changed Signal

---

vscode-trace-extension/src/trace-explorer/trace-tree.ts
vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts

When doing some testing on an internal extension, I noticed that we could no longer use the Open With TraceViewer command on Windows due to an invalid path failing (worked on Linux). 
I was able to trace the cause of this it to some code that uses .path instead of .fsPath, which is intended for use with the filesystem and scrubs out improper path values  (which is what caused our error!) I also fixed this in other areas of the code.
This fixes a critical issue which prevents users from opening traces in some cases.

Fix path failure preventing trace from opening

---

yarn.lock

Upgrade traceviewer-base and traceviewer-react-components dependencies. Upgrade also timeline-chart and tsp-typescipt-client.
Here are the new version:
traceviewer-base: 0.2.0-next.20231206220005.ff0943f.0+ff0943f
traceviewer-react-components:0.2.0-next.20231206220005.ff0943f.0
tsp-typescript-client: 0.4.0-next.20231117181831.54d71ef.0
timeline-chart: 0.3.0-next.20231117181926.6e20cc9.0
Perform also a yarn upgrade.

Upgrade traceviewer-base and traceviewer-react-components dependencies

---

README.md
package.json
vscode-trace-extension/package.json

Yarn watch script in root now executes 'yarn run watch' in each subdirectory and all outputs are streamed to a single terminal.
Tested to ensure that the changes in each directory are shown in Extension Development Host (webviews, extension, common) with the script.
README updated to reflect changes.
Developer QOL improvement.

Fix 'yarn watch' Script

---

RELEASE

That seems to be necessary for action "actions-gh-release" to work correctly for the first time.
Else we get the following error:
> 2024/01/30 22:49:25 Start running actions-gh-release 2024/01/30 22:49:25 Successfully parsed arguments
2024/01/30 22:49:25 Successfully parsed GitHub event pull_request
base-commit 939e8c2709300d010087478703073820c30bb509
head-commit 3e205211bf0b0401b7d8669a0e175517cc94bf13
2024/01/30 22:49:25 Failed to build release for RELEASE: tag must be specified
Note: the `GitHub release` job is still expected to fail in this PR - it should make it possible for #194 to succeed, once this here is merged and #194 is rebased.

Add bogus release tag in file RELEASE

---

.github/workflows/release.yml
RELEASE
doc/Publishing.md
package.json
vscode-trace-extension/package.json

This is the first try, so we may need to adjust some things to make it work in the end.
The idea is to update file `RELEASE`, adding a new release tag in there. Then we expect that tentative, automatically-generated release notes, will be added to this PR, for our review. Once we merge the PR, a GitHub release v0.2.0 should be created automatically in the repo, with attached release notes. The tag's creation should then trigger the job that published the extension to open-vsx.org.
Note: I picked v0.2.0 to avoid conflicting with the "vscode trace extension", that's already released on the Visual Studio Marketplace (which is currently at v0.1.44). I propose we go with a v1.0.0 version after discussions with other contributors, and after our release/publish infrastructure has been …

Trigger first release to open-vsx.org

---

.github/workflows/ci-cd.yml
RELEASE

When we previously created the v0.2.0 release using the RELEASE file, the corresponding GitHub release and git tag were created. However the publish job was not triggered. Testing on my fork, I concluded that the workflow needs to trigger on "create" tag, not on "push". One commit in this PR fixes this.
A slight side-effect of triggering the ci-cd workflow on "create" events is that it will now run also on branch creation. So it may run a bit more often than before. I think this is preferable for now, vs having complex "if:" conditions on each job in the workflow. 
Also, in a separate commit, we step the tag in file RELEASE to v0.2.1 to trigger a new release, which this time will hopefully trigger the publish job and successfully publish the extension to open-vsx. Afterwards,  I plan to …

[CI] Trigger publish job on tag creation, try again to publish

---

vscode-trace-extension/src/extension.ts
vscode-trace-extension/src/trace-explorer/trace-tree.ts

When the command 'openTraceFolder' is invoked from the Open Trace button, change the order so that the user is first prompted to select a trace folder. In order to do this, the openDialog() method is exported and is no longer called from the fileOpenHandler() method.
Use the selected trace to start the trace server using the trace server manager, which will select the proper contributor to start the server, based on the trace path.
Remove the execution of 'start-if-stopped' command from the startTraceServerIfAvailable() method, and make its pathToTrace parameter mandatory.
The fileOpenHandler() method is called last, and its traceUri parameter is now mandatory.
Fixes #183.

Use trace server manager with Open Trace command

---

.github/workflows/ci-cd.yml
.github/workflows/release.yml

It turns-out that using the GitHub token, that's automatically generated for each workflow run, does not allow for further workflow(s) being triggered. We were relying on that feature, for the "publish" job to trigger, after action "actions-gh-release" creates a git tag in the repo.
Instead, for that to work, we need to use an alternate token, from a committer. I will set such a token in the repo as a secret, under name "GH_COMMITTER_TOKEN"
Also a couple of minor upadates to the `ci-cd` workslow:
- use 'release' as workflow trigger to start publish job
- check before running job that the workflow was triggered by a release tag 'reference". These map to, e.g.: 
github.event_name:  release
github.ref:  refs/tags/v0.2.2

Use GitHub token from a committer in gh-release job

---

.github/workflows/ci-cd.yml

Add a job to publish the extension to the Visual Studio Marketplace, using the PAT setup for us by webmaster at org level.
This PR will not, by itself, trigger a publish to the Marketplace. Rather, the new job will trigger along with the existing job that publishes to the public open-vsx registry, when an eventual PR is merged, that modifies the `RELEASE` root file, adding a new release tag in there.
Note: Since the [Trace Server extension](https://github.com/eclipse-cdt-cloud/vscode-trace-server), depends on this extension here, we should be careful to publish this (Viewer) extension first to the Marketplace.

[CI] Infrastructure to enable publish to Marketplace 

---

RELEASE
vscode-trace-extension/package.json

Trigger release v0.2.3. If everything goes well, this time the extension should be published to the Visual Studio Markerplace, in addition to public OpenVSX (open-vsx.org).

Release v0.2.3

---

vscode-trace-extension/src/extension.ts
vscode-trace-extension/src/trace-explorer/available-views/trace-explorer-available-views-webview-provider.ts
vscode-trace-extension/src/trace-explorer/opened-traces/trace-explorer-opened-traces-webview-provider.ts
vscode-trace-extension/src/trace-explorer/properties/trace-explorer-properties-view-webview-provider.ts
vscode-trace-extension/src/trace-explorer/time-range/trace-explorer-time-range-data-webview-provider.ts
vscode-trace-extension/src/trace-explorer/trace-tree.ts
vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts

This commit provides proper handling of url configuration change. This fixes the issue of when the user changes the URL of the server, the user would need to reopen vscode so that all of the manangers can be initialized with the proper tspClientURL. With this commit, all tspClient dependent components are notified of a URL change.
Signed-off-by: Neel Gondalia ngondalia@blackberry.com

Proper Handling of the URL Configuration Change

---

vscode-trace-extension/package.json
vscode-trace-webviews/package.json
yarn.lock

The following 3PP dependency version, used in this repo and that currently fails the license check, has been deprecated:
`@fortawesome/fontawesome-common-types@0.3.0`
Eclipse Foundation ticket about its license:
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/12947
In theia-trace-extension, we had previously constrained the version range of the related dependency that pulls it, forcing a non-deprecated version to be used:
https://github.com/eclipse-cdt-cloud/theia-trace-extension/commit/e44236a292b3125e95454944c1ed8199e0692f52
I think we should do the same here.

[license] Get rid of version of 3PP version that's deprecated and fails the license check

---

README.md
vscode-trace-extension/src/external-api/external-api.ts

This commit provides API to attach and remove listeners to signalManager within the extension context.

Provide API to attach signal listeners to signalManager

---

RELEASE
vscode-trace-extension/package.json

Attempt again to publish the extension to the Visual Studio Marketplace.
We will only merge after the existing version of this extension (under a different publisher) is un-published from the Marketplace. We hope publishing will then succeed.

Release v0.2.4

---

vscode-trace-extension/package.json
vscode-trace-extension/src/extension.ts
vscode-trace-extension/src/test/extension-test.spec.ts
vscode-trace-extension/src/trace-explorer/available-views/trace-explorer-available-views-webview-provider.ts
vscode-trace-extension/src/trace-explorer/opened-traces/trace-explorer-opened-traces-webview-provider.ts
vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
vscode-trace-extension/src/utils/backend-tsp-client-provider.ts
vscode-trace-extension/src/utils/trace-server-status.ts
vscode-trace-webviews/src/trace-explorer/opened-traces/vscode-trace-explorer-opened-traces-widget.tsx

Adds `traceViewer.serverOn` VSCode context.
Replaces the use of `ReactPlaceholderWidget` with a welcome view.
Improves tracking of `trace-explorer.noExperiments` VSCode Context.

Improvements for accurate display of 'Welcome View' 

---

vscode-trace-common/src/messages/vscode-message-manager.ts
vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx
yarn.lock

This commit adds handling for the rowSelectionsChanged, contributeContextMenu and contextMenuItemClicked signals.
Depends on https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1044

Handle new signal for context menus and multi-row selection

---

vscode-trace-extension/src/extension.ts
vscode-trace-extension/src/trace-explorer/abstract-trace-explorer-provider.ts
vscode-trace-extension/src/trace-explorer/available-views/trace-explorer-available-views-webview-provider.ts
vscode-trace-extension/src/trace-explorer/opened-traces/trace-explorer-opened-traces-webview-provider.ts
vscode-trace-extension/src/trace-explorer/properties/trace-explorer-properties-view-webview-provider.ts
vscode-trace-extension/src/trace-explorer/time-range/trace-explorer-time-range-data-webview-provider.ts

Factors out common logic from all WebviewViewProviders into a new
AbstractTraceExplorerProvider abstract class.  This allows for shared
functionality between WebviewViewProviders to be modified in a single
place instead of each individual file.  DRYs out the code.

AbstractTraceExplorerProvider - Code Cleanup

---

README.md
vscode-trace-extension/package.json
vscode-trace-extension/src/extension.ts
vscode-trace-extension/src/external-api/external-api.ts
vscode-trace-extension/src/test/extension-test.spec.ts
vscode-trace-extension/src/trace-explorer/opened-traces/trace-explorer-opened-traces-webview-provider.ts
vscode-trace-extension/src/trace-explorer/trace-utils.ts
vscode-trace-extension/src/utils/trace-explorer-resource-type-handler.ts

This commit adds a handler that manages and detects resource type dialog that should be opened when opening a trace. It provides the ability to handle one or both file and folder trace types. If both is handled, a quick pick is shown to select which type of resource dialog should be opened. The functionality to control which trace type should be handle is provided through
the external API.

Handling of Files with Open Trace Button

---

RELEASE
vscode-trace-extension/package.json

Publish VSCode Trace Extension version 0.2.5.

Release v0.2.5

---

vscode-trace-extension/src/trace-explorer/abstract-trace-explorer-provider.ts

Fixed bug in postMessagetoWebview method of AbstractTraceExplorerProvider. The method returned on a valid command causing some views to break (Item Properties view)

Fixed message passing to webviews via AbstractTraceExplorerProvider

---

vscode-trace-extension/src/trace-explorer/opened-traces/trace-explorer-opened-traces-webview-provider.ts

see `TraceExplorerOpenedTracesViewProvider`
This was missed in commit https://github.com/eclipse-cdt-cloud/vscode-trace-extension/commit/77bf4f03c44677685bcb4ae92003d7f43f3a0be8.

Remove duplicate dispose listener in opened traces view provider

---

vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
vscode-trace-extension/src/utils/trace-server-status.ts
vscode-trace-webviews/src/trace-viewer/index.css
vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx

Add UI blocking overlay when server is offline.  This is to prevent the pending-requests issue in the remote use case and also prevents breaking ui states in the local use case.
Modifies the TraceServerConnectionStatusService to send a vscode message informing all active webviews (views and panels) of the change in server status. Adds a public method in TraceViewerPanel class that sends a vscode message to all active panels.

Add Semi-Opaque 'Server Offline' UI Blocker in TraceViewerPanels

---

vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx

This method is doing a check on the state to see if output descriptor already exists. In the case it is not found, it had a blocking call before updating the state. This resulted in subsequent signals received directly after the first one, to handle the same output descriptor again.
The outcome of this was that there would be descriptors with the same key being rendered causing errors.

Fix handling of state in doHandleOutputAddedMessage

---

.github/workflows/ci-cd.yml
.github/workflows/release.yml
README.md
lerna.json
package.json
vscode-trace-common/package.json
vscode-trace-extension/package.json
vscode-trace-webviews/package.json

Make this repo more similar to our other cdt-cloud repos:
- prevent triggering release-related jobs on forks
- document release process in root README
- add package.json scripts to help create the release commit and step version
Also, pre-format the various `package.json` and `lerna.json` files, as per lerna expectations. 
- indent using 4 spaces
- ordered dependencies
This is the format lerna enforces. Doing it now means that when we eventually use lerna to step the package.json versions, only the version change will be reflected in the result.
_Note: because of the many indentation-related changes, it might be easier to review using the "hide whitespace" option, in the "files changes" panel._

[ci] harmonize release doc, add dhelper scripts

---

vscode-trace-extension/src/trace-explorer/trace-utils.ts

Create panel after server instantiates the experiment and tie the panel name to the experiment name
Fixes the constant switching of tabs when multiple experiments opened with the same name

Handle multiple experiments with the same name

---

RELEASE
lerna.json
vscode-trace-common/package.json
vscode-trace-extension/package.json
vscode-trace-webviews/package.json

Publish VSCode Trace Extension v0.2.6

Release v0.2.6 (Patch)

---

vscode-trace-extension/src/extension.ts

This makes sure that the corresponding treeView is disposed properly.
This was missed in #244 that fixes #242.

Add Disposable of registered tree data provider to context subscription

---

vscode-trace-extension/package.json

Moves it to a lower / more appropriate part of the context menu.
Before:
After:

Move 'Open with Trace Viewer' option lower

---

vscode-trace-extension/src/trace-explorer/properties/trace-explorer-properties-view-webview-provider.ts

The PR fixes the following exception:
TypeError: Cannot read properties of undefined (reading 'UUID') at TraceExplorerItemPropertiesProvider.handleExperimentChanged

Fix exception in TraceExplorerItemPropertiesProvider

---

vscode-trace-extension/src/trace-explorer/abstract-trace-explorer-provider.ts
vscode-trace-extension/src/trace-viewer-panel/keyboard-shortcuts-panel.ts
vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts

- Update CSP for all webviews and allow data: for img-src/font-src
Fixes #251
- Remove vscode-resource/http/https/data from style-src for all webviews

  Update CSP for all webviews and allow data: for img-src/font-src

---

RELEASE
lerna.json
vscode-trace-common/package.json
vscode-trace-extension/package.json
vscode-trace-webviews/package.json

Note: This release has no code changes in comparison to version v0.2.7 and is to trigger a new publish to the vscode marketplace because previous publish was not validated successfully by the marketplace client.

Release v0.2.8 (Patch)

---

vscode-trace-extension/src/extension.ts
vscode-trace-extension/src/trace-explorer/trace-utils.ts

Wait for fileOpenHandler to finish, before refreshing the trace explorer context.

Fix issue #265

---

configs/license-check-config.json
configs/license-check-exclusions.json
package.json
vscode-trace-common/package.json
vscode-trace-extension/package.json
vscode-trace-webviews/package.json
vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx
yarn.lock

The new traceviewer packages contain the upgraded ag-grid packages, that removes several high-level vulnerabilities.
Also, in this repo here, we now only need the ag-grid styles package, "@ag-grid-community/styles" - the rest of ag-grid being obtained from `traceviewer-react-components`. Note that `ag-grid` now distributes themes containing both dark and light in the same .css file.
---
Performed a `yarn upgrade`: we went from 5 to 2 known vulnerabilities, as per "yarn audit":
Before:
5 vulnerabilities found - Packages audited: 926
Severity: 5 Moderate
After:
2 vulnerabilities found - Packages audited: 981
Severity: 2 Moderate

Upgrade to traceviewer* packages to v0.2.6, that include upgraded ag-grid

---

vscode-trace-common/package.json
vscode-trace-extension/package.json
vscode-trace-webviews/package.json
yarn.lock

We recently published updated version of "traceviewer-react-components" and "traceviewer-base", which themselves use updated versions of "timeline-chart" and "tsp-typescript-client". This commit updates the version range of related dependencies, requested in this repo, so that the latest versions are picked-up.

Update to latest traceviewer-* dependencies

---

vscode-trace-common/tsconfig.json
vscode-trace-extension/tsconfig.json
vscode-trace-webviews/tsconfig.json

The presence of trailing commas within tsconfig.json files doesn't seem to adversely affect the normal build process of vscode-trace-extension, but it seems to lead to build-time problems if you try to incorporate vscode-trace-extension into a monorepo for building a Theia-based product.  For example, this is an example snippet when running "yarn" from top-level of such a monorepo of Theia-based product:
$ yarn -s compile:references && lerna run prepare && yarn -s compile
ParseError in file: /home/build/git/theia-based-product/vscode-extensions/vscode-trace-extension/vscode-trace-common/tsconfig.json
SyntaxError: Expected double-quoted property name in JSON at position 118
at JSON.parse (<anonymous>)
at readJsonFile (/home/build/git/theia-based-product/scripts/compile-references.js:147:21) …

remove trailing commas from tsconfig.json file instances

---

vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts

Send TRACEVIEWERTAB_ACTIVATED signal when setting the experiment after a experiment is opened. This will select the experiment in the opened traces view which then will broadcast the EXPERIMENT_SELECTED signal to update other webviews.
Fixes #264

Select experiment when opening from open command

---

vscode-trace-common/package.json
vscode-trace-common/src/signals/vscode-signal-converter.ts
vscode-trace-extension/package.json
vscode-trace-webviews/package.json
yarn.lock

This upgrade will pull in the following component releases. See links below for the change logs:
- `traceviewer-base` and `traceviewer-react-components` **v0.4.2**
- https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1127
- https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1142
- https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1145
- https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1148
- `timeline-chart` **v0.4.1**
- https://github.com/eclipse-cdt-cloud/timeline-chart/pull/300
- https://github.com/eclipse-cdt-cloud/timeline-chart/pull/305 
- `tsp-typescript-client` **v0.5.1**
- https://github.com/eclipse-cdt-cloud/tsp-typescript-client/pull/120
- https://github.com/eclipse-cdt-cloud/tsp-typescript-client/pull/122
Signed-off-by: …

Upgrade traceviewer components

---

README.md

This PR adds the following commits that updates the README.md file:
- Move note about initial contribution to own chapter
- Add instructions for building from local sources using yarn link 
To be able to build and test changes in the trace viewer libraries during development, the local source code needs to linked to the vscode-trace-extension. This commit adds instructions on how to do that and what to be aware of in case there are build or runtime errors.

Add instructions for building from local sources using yarn link

---

vscode-trace-common/src/messages/vscode-message-manager.ts
vscode-trace-extension/src/trace-explorer/properties/trace-explorer-properties-view-webview-provider.ts
vscode-trace-webviews/src/trace-explorer/properties/vscode-trace-explorer-properties-widget.tsx

The intention of this patch is to achieve the following runtime behavior:
If a loaded trace has a "Source" column, and if the value of that column is of the form file:line, then highlighting the event in question, and clicking on the "Source" value that shows up in Item Properties shall open the corresponding file in a VSCode editor, and position the cursor on the corresponding line number, if said file exists.

Implement source lookup in Item Properties view

---

vscode-trace-extension/src/trace-explorer/trace-utils.ts

The trace detection algorithm checks recursively for CTF traces. If no CTF trace are found under the root directory, then use the root directory as trace directory. The trace server back-end will validate if this path points to a valid trace or not.
With this it's now possible to open traces that are directories other than CTF.
Note that only a single trace can be opened in the experiment and not set of traces, which is currently only supported with CTF traces.
Examples trace type: uftrace

Support of directory traces other than CTF

---

README.md
vscode-trace-common/package.json
vscode-trace-extension/package.json
vscode-trace-extension/src/external-api/external-api.ts
vscode-trace-extension/src/trace-explorer/available-views/trace-explorer-available-views-webview-provider.ts
vscode-trace-extension/src/trace-explorer/opened-traces/trace-explorer-opened-traces-webview-provider.ts
vscode-trace-extension/src/trace-explorer/properties/trace-explorer-properties-view-webview-provider.ts
vscode-trace-extension/src/trace-explorer/time-range/trace-explorer-time-range-data-webview-provider.ts
vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
vscode-trace-webviews/package.json
vscode-trace-webviews/src/trace-explorer/available-views/vscode-trace-explorer-views-widget.tsx
vscode-trace-webviews/src/trace-explorer/opened-traces/vscode-trace-explorer-opened-traces-widget.tsx
vscode-trace-webviews/src/trace-explorer/properties/vscode-trace-explorer-properties-widget.tsx
vscode-trace-webviews/src/trace-explorer/time-range/vscode-time-range-data-widget.tsx
vscode-trace-webviews/src/trace-viewer/vscode-trace-viewer-container.tsx
yarn.lock

Replaces Signal keys with strings for event handlers Replaces fire* methods with emit methods

Refactor for SignalManager changes

---

vscode-trace-extension/src/trace-explorer/trace-utils.ts

Fixes #296.
Triggers an update to the 'trace-explorer.noExperiments' context after a trace or experiment is opened.
The steps to reproduce the bug can be found in #296.
The bug can be reproduced on `master`
The bug should be fixed on this branch.
When the server is online, the context is properly updated by a vscode-message sent from the frontend recieved by the backend.
```typescript
// 105-112 vscode-trace-explorer-opened-traces-widget.tsx
private initialized = false;
protected doHandleOpenedTracesChanged(payload: OpenedTracesUpdatedSignalPayload): void {
if (!this.initialized) {
this.initialized = true;
return;
}
this._signalHandler.updateOpenedTraces(payload.getNumberOfOpenedTraces());
}
```
```typescript
// 116-118 trace-explorer-opened-traces-webview-provider.ts
case …
```

Update 'noExperiments' context after trace open

---

README.md
configs/errors.eslintrc.json
vscode-trace-extension/package.json
vscode-trace-extension/src/extension.ts
vscode-trace-extension/src/trace-explorer/abstract-trace-explorer-provider.ts
vscode-trace-extension/src/trace-explorer/available-views/trace-explorer-available-views-webview-provider.ts
vscode-trace-extension/src/trace-explorer/opened-traces/trace-explorer-opened-traces-webview-provider.ts
vscode-trace-extension/src/trace-viewer-panel/keyboard-shortcuts-panel.ts
vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts
vscode-trace-extension/src/utils/backend-tsp-client-provider.ts

The vscode-trace-extension code is written so that some REST calls towards the server are done by the vscode backend, and some from the vscode frontend (webviews). In some situations can be useful to be able to specify different URLs for the REST calls, depending on where the REST call is done (vscode frontend or backend). For example when deploying on a k8s cluster, where the vscode backend can communicate to the trace server without going through an ingress.
This PR add the setting to be able to select the URL used from the vscode backend. 
To make sure that the added feature works as expected (i.e. the REST calls are done to different URLs and/or ports), a simple test setup can be configured locally by:
- starting 2 trace-servers on 2 different ports
- ```trace-server -data …
```

Add extra configuration parameter for vscode backend URL

---

vscode-trace-extension/src/extension.ts
vscode-trace-extension/src/trace-explorer/abstract-trace-explorer-provider.ts
vscode-trace-extension/src/trace-explorer/properties/trace-explorer-properties-view-webview-provider.ts

The initialization of webview views can be tricky. There are the 4 trace explorer views and also welcome view, one set of which should be displayed at any given moment, depending on context variables. However it can be possible to have jitter initially if the context variables change value quickly, which can result in webview views being resolved again without the "onDispose" event being sent. When this happens, the webview views have no opportunity to unregister their event listeners, causing leaks.
To address the jitter, context variables `trace-explorer.noExperiments` and `traceViewer.serverUp` are initialized at activation with values that will prevent the trace explorer webview views being "resolved", causing an unambiguous situation where the welcome view will be displayed instead, …

Minimize jitter related to creation of trace explorer webview views

---

vscode-trace-extension/src/extension.ts
vscode-trace-extension/src/trace-explorer/trace-utils.ts
vscode-trace-extension/src/trace-viewer-panel/trace-viewer-webview-panel.ts

Enhances "traces.openTraceFile" command to return the UUID of the opened experiment (rather than returning a void value in all cases).  Provides a new command "traces.removeTrace" that accepts a UUID referring to an experiment (obtained by an earlier call to traces.openTraceFile), and removes any open trace viewer panels associated with that experiment, as well as removing it from the experiment manager.
These changes allow trace opening and closing to be accomplished programmatically from other vscode extensions.  Without these changes, an experiment must be closed from within the trace viewer UI, even if another vscode extension was used to delete an underlying trace file.
From a vscode extension other than vscode-trace-extension, invoke the traces.openTraceFile command with valid …

Programmatic experiment deletion

---

local-libs/traceviewer-libs/base/package.json

When the traceviewer-libs git subtree was initially added, running prettier (yarn format:check) would fail locally. This was since determine to be because this repo here was already pulling a more recent version of "prettier" than the theia extension repo: v3.x vs v2.x.
The local version of the subtree already has the libraries' code adapted to pass the check with prettier@3. That version was explicitly added as a devDependency to the traceviewer- react-components library, but for completeness, we now add it to traceviwewer-base as well, to be sure the format check will be identical in both repositories, no matter the version of prettier that may be pulled in the root package.json or other components, in either / both repositories.
Confirm that CI passes
N/A

[traceviewer-base] explicitly request recent prettier dependency

---

local-libs/traceviewer-libs/base/package.json
local-libs/traceviewer-libs/react-components/package.json
local-libs/traceviewer-libs/react-components/src/components/abstract-tree-output-component.tsx
local-libs/traceviewer-libs/react-components/src/components/abstract-xy-output-component.tsx
local-libs/traceviewer-libs/react-components/src/components/generic-xy-output-component.tsx
local-libs/traceviewer-libs/react-components/src/components/trace-context-component.tsx
local-libs/traceviewer-libs/react-components/src/components/utils/xy-shared.ts
vscode-trace-common/package.json

Adds the generic XY view as introduced in [eclipse-cdt-cloud/trace-server-protocol#114](https://github.com/eclipse-cdt-cloud/trace-server-protocol/issues/114).
The initial design intended to show selection data in the bar chart (similar to the data tree view). This was revised during implementation because the legacy XY endpoint does not show selection, and adding extra bars for selection would be visually confusing with a time-based x-axis. Consequently, selection is no longer displayed in this view.
This change requires the updates from [eclipse-cdt-cloud/tsp-typescript-client#138](https://github.com/eclipse-cdt-cloud/tsp-typescript-client/pull/138).
The corresponding server and protocol updates are already merged in:
* https://github.com/eclipse-tracecompass/org.eclipse.tracecompass/pul …

Add generic XY view
